In [29]:
# Performed as a part of curriculum at Great Learning
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils

In [30]:
import numpy
numpy.random.seed(7)
alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
char_to_int=dict((c,i) for i,c in enumerate(alphabet))
int_to_char=dict((i,c) for i,c in enumerate(alphabet))

In [31]:
seq_length=1
dataX=[]
dataY=[]

In [32]:
for i in range(0,len(alphabet)-seq_length,1):
  seq_in=alphabet[i:i+seq_length]
  seq_out=alphabet[i+seq_length]
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out])
  print(seq_in,'**',seq_out)

A ** B
B ** C
C ** D
D ** E
E ** F
F ** G
G ** H
H ** I
I ** J
J ** K
K ** L
L ** M
M ** N
N ** O
O ** P
P ** Q
Q ** R
R ** S
S ** T
T ** U
U ** V
V ** W
W ** X
X ** Y
Y ** Z


In [33]:
x=numpy.reshape(dataX,(len(dataX),seq_length,1))
x.shape

(25, 1, 1)

In [34]:
x=x/float(len(alphabet))
y=np_utils.to_categorical(dataY)

In [35]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [36]:
y.shape

(25, 26)

In [37]:
model=Sequential()
model.add(LSTM(32,input_shape=(x.shape[1],x.shape[2])))
model.add(Dense(y.shape[1],activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=500,batch_size=1,verbose=2)

Epoch 1/500
25/25 - 1s - loss: 3.2675 - accuracy: 0.0000e+00
Epoch 2/500
25/25 - 0s - loss: 3.2597 - accuracy: 0.0000e+00
Epoch 3/500
25/25 - 0s - loss: 3.2567 - accuracy: 0.0400
Epoch 4/500
25/25 - 0s - loss: 3.2540 - accuracy: 0.0400
Epoch 5/500
25/25 - 0s - loss: 3.2512 - accuracy: 0.0400
Epoch 6/500
25/25 - 0s - loss: 3.2483 - accuracy: 0.0400
Epoch 7/500
25/25 - 0s - loss: 3.2454 - accuracy: 0.0400
Epoch 8/500
25/25 - 0s - loss: 3.2428 - accuracy: 0.0400
Epoch 9/500
25/25 - 0s - loss: 3.2397 - accuracy: 0.0400
Epoch 10/500
25/25 - 0s - loss: 3.2364 - accuracy: 0.0400
Epoch 11/500
25/25 - 0s - loss: 3.2330 - accuracy: 0.0400
Epoch 12/500
25/25 - 0s - loss: 3.2293 - accuracy: 0.0000e+00
Epoch 13/500
25/25 - 0s - loss: 3.2257 - accuracy: 0.0000e+00
Epoch 14/500
25/25 - 0s - loss: 3.2215 - accuracy: 0.0000e+00
Epoch 15/500
25/25 - 0s - loss: 3.2177 - accuracy: 0.0000e+00
Epoch 16/500
25/25 - 0s - loss: 3.2129 - accuracy: 0.0000e+00
Epoch 17/500
25/25 - 0s - loss: 3.2083 - accuracy: 0.

In [38]:
scores=model.evaluate(x,y,verbose=0)
print("Model accuracy: %.2f%%" %(scores[1]*100))

Model accuracy: 80.00%


In [39]:
test=dataX[4]
test=numpy.reshape(test,(1,len(test),1))
test=test/float(len(alphabet))
pred=model.predict(test,verbose=0)
pred

array([[4.94441110e-08, 8.79252981e-03, 3.92918140e-02, 1.09375983e-01,
        1.94661587e-01, 2.29512483e-01, 1.83334231e-01, 1.18003055e-01,
        6.46644682e-02, 3.16364504e-02, 1.24849770e-02, 5.37046185e-03,
        1.91752228e-03, 6.49720605e-04, 2.08150726e-04, 7.00604942e-05,
        1.95206267e-05, 5.07893719e-06, 1.35445350e-06, 3.53134254e-07,
        8.76548540e-08, 1.76657391e-08, 3.40604189e-09, 9.46740575e-10,
        2.41414805e-10, 7.87370169e-11]], dtype=float32)

In [40]:
ind=numpy.argmax(pred)
res=int_to_char[ind]
res

'F'

In [41]:
# Creating a multichar to one char output

In [42]:
import numpy
numpy.random.seed(7)
alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
char_to_int=dict((c,i) for i,c in enumerate(alphabet))
int_to_char=dict((i,c) for i,c in enumerate(alphabet))
seq_length=3
dataX=[]
dataY=[]
for i in range(0,len(alphabet)-seq_length,1):
  seq_in=alphabet[i:i+seq_length]
  seq_out=alphabet[i+seq_length]
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out])
  print(seq_in,'**',seq_out)
x=numpy.reshape(dataX,(len(dataX),seq_length,1))

ABC ** D
BCD ** E
CDE ** F
DEF ** G
EFG ** H
FGH ** I
GHI ** J
HIJ ** K
IJK ** L
JKL ** M
KLM ** N
LMN ** O
MNO ** P
NOP ** Q
OPQ ** R
PQR ** S
QRS ** T
RST ** U
STU ** V
TUV ** W
UVW ** X
VWX ** Y
WXY ** Z


In [43]:
x.shape

(23, 3, 1)

In [44]:
x=x/float(len(alphabet))
y=np_utils.to_categorical(dataY)

In [45]:
y[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [46]:
y.shape

(23, 26)

In [51]:
model=Sequential()
model.add(LSTM(32,input_shape=(x.shape[1],x.shape[2])))
model.add(Dense(y.shape[1],activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=500,batch_size=1,verbose=2)

Epoch 1/500
23/23 - 1s - loss: 3.2673 - accuracy: 0.0000e+00
Epoch 2/500
23/23 - 0s - loss: 3.2521 - accuracy: 0.0000e+00
Epoch 3/500
23/23 - 0s - loss: 3.2442 - accuracy: 0.0000e+00
Epoch 4/500
23/23 - 0s - loss: 3.2357 - accuracy: 0.0000e+00
Epoch 5/500
23/23 - 0s - loss: 3.2280 - accuracy: 0.0000e+00
Epoch 6/500
23/23 - 0s - loss: 3.2184 - accuracy: 0.0000e+00
Epoch 7/500
23/23 - 0s - loss: 3.2095 - accuracy: 0.0000e+00
Epoch 8/500
23/23 - 0s - loss: 3.1993 - accuracy: 0.0435
Epoch 9/500
23/23 - 0s - loss: 3.1882 - accuracy: 0.0000e+00
Epoch 10/500
23/23 - 0s - loss: 3.1749 - accuracy: 0.0435
Epoch 11/500
23/23 - 0s - loss: 3.1610 - accuracy: 0.0435
Epoch 12/500
23/23 - 0s - loss: 3.1469 - accuracy: 0.0435
Epoch 13/500
23/23 - 0s - loss: 3.1313 - accuracy: 0.0000e+00
Epoch 14/500
23/23 - 0s - loss: 3.1127 - accuracy: 0.0000e+00
Epoch 15/500
23/23 - 0s - loss: 3.0945 - accuracy: 0.0000e+00
Epoch 16/500
23/23 - 0s - loss: 3.0823 - accuracy: 0.0000e+00
Epoch 17/500
23/23 - 0s - loss: 3

In [52]:
scores=model.evaluate(x,y,verbose=0)
print("Model accuracy: %.2f%%" %(scores[1]*100))

Model accuracy: 95.65%


In [53]:
test=dataX[4]
test=numpy.reshape(test,(1,len(test),1))
test=test/float(len(alphabet))
pred=model.predict(test,verbose=0)
pred

array([[7.9032221e-09, 1.4029967e-08, 1.1737600e-08, 7.7799820e-09,
        2.3041383e-05, 9.2425721e-04, 2.0455483e-02, 9.5360178e-01,
        2.1797873e-02, 2.2336554e-03, 5.2483170e-04, 3.1790088e-04,
        5.5055443e-05, 3.2309206e-05, 2.5243253e-06, 2.5895428e-05,
        1.2483916e-06, 8.4480388e-07, 3.1634092e-06, 5.2348845e-08,
        3.6135397e-08, 2.8400404e-08, 1.1831239e-08, 1.7756392e-08,
        1.0082265e-08, 3.1882685e-08]], dtype=float32)

In [54]:
ind=numpy.argmax(pred)
res=int_to_char[ind]
res

'H'